FROM mcr.microsoft.com/dotnet/sdk:8.0 as build

WORKDIR /app
EXPOSE 80

# copy all .csproj files and restore as distinct layers.  Use of the same COPY command
# for every dockerfile in the project to take advantage of docker caching
COPY car-auction.sln car-auction.sln
COPY AuctionService/AuctionService.csproj AuctionService/AuctionService.csproj
COPY SearchService/SearchService.csproj SearchService/SearchService.csproj
COPY GatewayService/GatewayService.csproj GatewayService/GatewayService.csproj
COPY Contracts/Contracts.csproj Contracts/Contracts.csproj
COPY IdentityService/IdentityService.csproj IdentityService/IdentityService.csproj

# restore package deps
RUN dotnet restore car-auction.sln

# Copy the app folders over
COPY AuctionService AuctionService
COPY Contracts Contracts

WORKDIR /app/AuctionService
RUN dotnet publish -c Release -o /app/out

# build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 as runtime
WORKDIR /app

COPY --from=build /app/out .
ENTRYPOINT [ "dotnet", "AuctionService.dll" ]